configs:
  # application-web 
- id: application
  config:
    name:
      type: compound
      format: "{{ .appName }}"
      references:
        - appName
    template: application.json
    parameters:
      appName:
        name: TEMPLATE_APP_NAME
        type: environment
      rumPercentage: 
        name: TEMPLATE_APP_RUM_PERCENTAGE
        type: environment
  type:
    api: application-web
# app-detection-rule 
- id: application-detection-rule
  config:
    name:
      configType: application-web
      configId: application
      property: name
      type: reference
    template: application-detection-rule.json
    skip: false
    parameters:
      #reference id of application
      applicationId:
        configType: application-web
        configId: application
        property: id
        type: reference
      pattern:
        name: TEMPLATE_APP_URL_PATTERN
        type: environment
      matcher: 
        name: TEMPLATE_APP_MATCHER
        type: environment
  type:
    settings:
      schema: builtin:rum.web.app-detection
      schemaVersion: 2.1.1
      scope: environment
 # management-zone 
- id: management-zone
  config:
    name: 
      name: TEMPLATE_APP_MANAGEMENT_ZONE
      type: environment
    parameters:
      environment:
        name: TEMPLATE_APP_MANAGEMENT_ZONE
        type: environment
    template: management-zone.json
    skip: false
  type:
    settings:
      schema: builtin:management-zones
      schemaVersion: 1.0.6
      scope: environment
  # alerting-profile
- id: alerting-profile
  config:
    name:
      name: TEMPLATE_APP_MANAGEMENT_ZONE
      type: environment
    parameters:
      mzId: [ "template",  "builtin:management-zones","management-zone", "id" ]
    template: alerting-profile.json
    skip: false
  type:
    settings:
      schema: builtin:alerting.profile
      schemaVersion: 8.4.1
      scope: environment
# notification 
- id: email-team
  config:
    name: 
      name: TEMPLATE_APP_MANAGEMENT_ZONE
      type: environment
    parameters:
      alertingProfile: [ "template",  "builtin:alerting.profile","alerting-profile", "id" ]
      recipient: 
        name: TEMPLATE_APP_ALERT_RECIPIENTS
        type: environment
    template: notification.json
    skip: false
  type:
    settings:
      schema: builtin:problem.notifications
      schemaVersion: 1.4.11
      scope: environment
