configs:
  - id: synthetic_test
    config:
      name: google - monaco
      parameters:
        syntheticLocation:
          type: value
          value:
            location_id_one: <REPLACE WITH SYNTHETIC LOCATION ID> ##e.g. SYNTHETI_LOCATION-123445
            location_id_two: <REPLACE WITH SYNTHETIC LOCATION ID> ##e.g. SYNTHETI_LOCATION-123445
        monitorURL:
          type: value
          value:
            url_name: www.google.com
      template: synthetic_test.json
      skip: false
    type:
      api: synthetic-monitor
